
#Writing your pyproject.toml - Python Packaging User Guide
#https://packaging.python.org/en/latest/guides/writing-pyproject-toml/




[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "qt_by_example"
version = "2020.0.0"
dependencies = [
  "httpx",
  "gidgethub[httpx]>4.0.0",
  "django>2.1; os_name != 'nt'",
  "django>2.0; os_name == 'nt'",
]
requires-python = ">=3.8"
authors = [
  {name = "Russ Hensel", email = "contact via git hub"},
]
maintainers = [
  {name = "Russ Hensel", email = "contact via git hub"}
]
description = "Example code using qt"
readme = "README.md"
license = {file = "LICENSE.txt"}
keywords = ["qt", "python", "pyqt", "pyqt5", "GUI"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]

[project.optional-dependencies]
gui = ["PyQt5"]
cli = [
  "rich",
  "click",
]

[project.urls]
Homepage = "https://example.com"
Documentation = "https://readthedocs.org"
Repository = "https://github.com/me/spam.git"
"Bug Tracker" = "https://github.com/me/spam/issues"
Changelog = "https://github.com/me/spam/blob/master/CHANGELOG.md"

[project.scripts]
spam-cli = "spam:main_cli"

[project.gui-scripts]
spam-gui = "spam:main_gui"

[project.entry-points."spam.magical"]
tomatoes = "spam:main_tomatoes"